window.MN_STORAGE_KEY='mnBeautyCompleteConfig';
window.MN_DEFAULTS={
 nomeMarca:'MN Beauty',monograma:'MN',descricaoMarca:'Brow Design Studio',profissional:'Mayane Novaes',assinatura:'Mayane',seoDescricao:'Design de sobrancelhas personalizado, com técnica, naturalidade e atendimento individual.',
 corPrincipal:'#9f6d64',corEscura:'#5a3734',corFundo:'#f3eee9',corTexto:'#1b1618',tema:'light',fonteTitulo:'Italiana',fonteTexto:'DM Sans',bordas:'organic',animacoes:'suave',
 menuExperiencia:'Experiência',menuServicos:'Serviços',menuResultados:'Resultados',menuGaleria:'Galeria',menuSobre:'Sobre',menuFaq:'FAQ',menuContato:'Contato',menuAgendar:'Agendar horário',
 heroEyebrow:'Design • Simetria • Naturalidade',heroTitulo1:'Sobrancelhas que',heroTitulo2:'expressam você.',heroTexto:'Mapeamento facial e design personalizado para valorizar seu olhar sem perder a naturalidade.',heroBotao:'Agendar meu design',heroLink:'Conhecer procedimentos',heroProvaTitulo:'Atendimento individual',heroProvaTexto:'com avaliação antes de cada procedimento.',heroEtiqueta:'Resultado sob medida',heroEtiquetaTexto:'Natural, preciso e elegante.',heroImagem:'',
 metodoEyebrow:'A experiência MN',metodoTitulo:'Seu olhar merece um projeto exclusivo.',metodoIntroducao:'Cada atendimento começa com análise facial, conversa e planejamento para que o resultado respeite seus traços.',
 metodo:[{titulo:'Análise e escuta',texto:'Entendo suas preferências, rotina e o resultado que você deseja.'},{titulo:'Mapeamento facial',texto:'Estudo proporções, simetria e pontos estratégicos do seu rosto.'},{titulo:'Design personalizado',texto:'Execução precisa, respeitando a estrutura natural dos fios.'},{titulo:'Orientação final',texto:'Cuidados simples para manter o resultado bonito por mais tempo.'}],
 servicosEyebrow:'Procedimentos',servicosTitulo:'Técnicas para realçar seu olhar.',servicosTexto:'Escolha o procedimento ideal ou fale comigo para receber uma indicação personalizada.',
 servicos:[{nome:'Design Personalizado',categoria:'Precisão e equilíbrio',descricao:'Mapeamento e remoção estratégica dos fios para valorizar o formato natural.',preco:'A partir de R$ 45',duracao:'40 min',destaque:true,imagem:''},{nome:'Design com Henna',categoria:'Definição temporária',descricao:'Design completo com aplicação de henna para preencher falhas e destacar o desenho.',preco:'A partir de R$ 60',duracao:'50 min',destaque:false,imagem:''},{nome:'Brow Lamination',categoria:'Alinhamento dos fios',descricao:'Técnica para alinhar, encorpar e criar um efeito moderno e elegante.',preco:'A partir de R$ 120',duracao:'70 min',destaque:false,imagem:''}],
 resultadosEyebrow:'Resultados reais',resultadosTitulo:'Detalhes que transformam a expressão.',resultadosTexto:'O objetivo é criar equilíbrio, definição e leveza, respeitando o formato natural dos fios.',antesLabel:'Antes',depoisLabel:'Depois',antesImagem:'',depoisImagem:'',
 estatisticas:[{valor:'100%',rotulo:'personalizado'},{valor:'1:1',rotulo:'atendimento exclusivo'},{valor:'∞',rotulo:'possibilidades'}],
 galeriaEyebrow:'Portfólio',galeriaTitulo:'Olhares que contam histórias.',galeriaTexto:'Uma seleção de resultados para você conhecer meu estilo de trabalho.',galeria:[],
 sobreEyebrow:'Sua brow designer',sobreLead:'Técnica, sensibilidade e atenção aos detalhes para criar sobrancelhas elegantes e naturais.',sobreTexto:'Meu trabalho une análise facial, precisão e escuta. Cada design é planejado de forma única, porque nenhuma expressão é igual à outra.',sobreBotao:'Conhecer meu trabalho',profissionalImagem:'',
 depoimentosEyebrow:'Experiências',depoimentosTitulo:'O que minhas clientes dizem.',depoimentos:[{nome:'Cliente MN Beauty',texto:'Amei o cuidado em cada detalhe. Minha sobrancelha ficou definida, mas totalmente natural.',estrelas:5,foto:''},{nome:'Cliente MN Beauty',texto:'Finalmente encontrei um design que respeita meu rosto. O atendimento foi impecável.',estrelas:5,foto:''}],
 faqEyebrow:'Dúvidas frequentes',faqTitulo:'Antes de agendar.',faqTexto:'Respostas rápidas para as perguntas mais comuns sobre os procedimentos.',faq:[{pergunta:'O design de sobrancelhas dói?',resposta:'Pode haver um leve desconforto durante a remoção dos fios, mas o procedimento é rápido e realizado com bastante cuidado.'},{pergunta:'Quanto tempo dura o resultado?',resposta:'Em média, de 15 a 25 dias, dependendo do crescimento dos fios e dos cuidados de cada cliente.'},{pergunta:'Como escolher o procedimento ideal?',resposta:'No início do atendimento faço uma avaliação e indico a técnica mais adequada ao seu objetivo.'}],
 localEyebrow:'Atendimento',localTitulo:'Onde encontrar a MN Beauty.',endereco:'Informe o endereço pelo editor.',maps:'',horarios:[{dia:'Segunda',hora:'Fechado'},{dia:'Terça a sexta',hora:'09:00 — 19:00'},{dia:'Sábado',hora:'09:00 — 17:00'},{dia:'Domingo',hora:'Fechado'}],
 agendamentoEyebrow:'Seu momento começa aqui',agendamentoTitulo:'Pronta para transformar seu olhar?',agendamentoTexto:'Fale comigo pelo WhatsApp e encontre o melhor procedimento, data e horário para você.',whatsappBotao:'Agendar pelo WhatsApp',instagramBotao:'Ver Instagram',agendamentoNota:'Atendimento com hora marcada.',
 whatsapp:'https://wa.me/5500000000000',instagram:'https://instagram.com/',facebook:'',tiktok:'',pinterest:'',threads:'',rodapeTexto:'© {ano} MN Beauty. Todos os direitos reservados.'
};
window.MN_getConfig=function(){try{return {...MN_DEFAULTS,...JSON.parse(localStorage.getItem(MN_STORAGE_KEY)||'{}')}}catch{return {...MN_DEFAULTS}}};
