const STORAGE_KEY=MN_STORAGE_KEY, defaults=MN_DEFAULTS;
let config=MN_getConfig(),dirty=false,toastTimer;
const form=document.getElementById('editorForm'),preview=document.getElementById('sitePreview'),nav=document.getElementById('editorNav');
const sections=[
 ['marca','Marca'],['visual','Visual'],['hero','Hero'],['metodo','Método'],['servicos','Serviços'],['resultados','Resultados'],['galeria','Galeria'],['sobre','Sobre'],['social','Social'],['dados','Dados']
];
const field=(key,label,type='text',help='')=>({key,label,type,help});
const panels={
 marca:{kicker:'Identidade',title:'Marca e SEO',desc:'Informações centrais e dados para buscadores.',fields:[field('nomeMarca','Nome da marca'),field('monograma','Monograma'),field('descricaoMarca','Descrição curta'),field('profissional','Nome da profissional'),field('assinatura','Assinatura'),field('seoDescricao','Descrição para buscadores','textarea'),field('rodapeTexto','Texto do rodapé')]},
 visual:{kicker:'Direção visual',title:'Cores e estilo',desc:'Personalize aparência, fontes e movimento.',fields:[field('corPrincipal','Cor principal','color'),field('corEscura','Cor escura','color'),field('corFundo','Cor de fundo','color'),field('corTexto','Cor do texto','color'),field('tema','Tema','select:light|Claro,dark|Escuro'),field('fonteTitulo','Fonte dos títulos','select:Italiana|Italiana,Playfair Display|Playfair Display,Cormorant Garamond|Cormorant Garamond'),field('fonteTexto','Fonte dos textos','select:DM Sans|DM Sans,Manrope|Manrope'),field('bordas','Formato das bordas','select:organic|Orgânico,soft|Suave,square|Reto'),field('animacoes','Animações','select:suave|Suaves,none|Desativadas')]},
 hero:{kicker:'Primeira impressão',title:'Hero e menu',desc:'Controle os textos iniciais, navegação e imagem principal.',fields:[field('menuExperiencia','Menu: Experiência'),field('menuServicos','Menu: Serviços'),field('menuResultados','Menu: Resultados'),field('menuGaleria','Menu: Galeria'),field('menuSobre','Menu: Sobre'),field('menuFaq','Menu: FAQ'),field('menuContato','Menu: Contato'),field('menuAgendar','Botão do menu'),field('heroEyebrow','Etiqueta'),field('heroTitulo1','Título — linha 1'),field('heroTitulo2','Título — linha 2'),field('heroTexto','Apresentação','textarea'),field('heroBotao','Botão principal'),field('heroLink','Link secundário'),field('heroProvaTitulo','Prova — título'),field('heroProvaTexto','Prova — texto'),field('heroEtiqueta','Cartão — etiqueta'),field('heroEtiquetaTexto','Cartão — texto'),field('heroImagem','Imagem principal','image')]},
 metodo:{kicker:'Experiência',title:'Método de atendimento',desc:'Explique o processo e organize suas etapas.',fields:[field('metodoEyebrow','Etiqueta'),field('metodoTitulo','Título'),field('metodoIntroducao','Introdução','textarea')],collection:{key:'metodo',label:'Etapas',template:{titulo:'Nova etapa',texto:'Descreva esta etapa.'},fields:[['titulo','Título'],['texto','Descrição','textarea']]}},
 servicos:{kicker:'Procedimentos',title:'Serviços',desc:'Adicione quantos procedimentos quiser.',fields:[field('servicosEyebrow','Etiqueta'),field('servicosTitulo','Título'),field('servicosTexto','Introdução','textarea')],collection:{key:'servicos',label:'Procedimentos',template:{nome:'Novo procedimento',categoria:'Categoria',descricao:'Descrição',preco:'Consulte',duracao:'',destaque:false,imagem:''},fields:[['nome','Nome'],['categoria','Categoria'],['descricao','Descrição','textarea'],['preco','Preço'],['duracao','Duração'],['destaque','Destaque','checkbox'],['imagem','Imagem','image']]}},
 resultados:{kicker:'Prova visual',title:'Resultados',desc:'Edite textos, métricas e comparador antes/depois.',fields:[field('resultadosEyebrow','Etiqueta'),field('resultadosTitulo','Título'),field('resultadosTexto','Texto','textarea'),field('antesLabel','Rótulo antes'),field('depoisLabel','Rótulo depois'),field('antesImagem','Imagem antes','image'),field('depoisImagem','Imagem depois','image')],collection:{key:'estatisticas',label:'Indicadores',template:{valor:'100%',rotulo:'novo indicador'},fields:[['valor','Valor'],['rotulo','Legenda']]}},
 galeria:{kicker:'Portfólio',title:'Galeria de resultados',desc:'Adicione fotos e legendas. Clique nas fotos do site para ampliar.',fields:[field('galeriaEyebrow','Etiqueta'),field('galeriaTitulo','Título'),field('galeriaTexto','Texto','textarea')],collection:{key:'galeria',label:'Fotos',template:{imagem:'',legenda:'Novo resultado'},fields:[['imagem','Imagem','image'],['legenda','Legenda']]}},
 sobre:{kicker:'Autoridade',title:'Sobre e depoimentos',desc:'Apresente sua história e as experiências das clientes.',fields:[field('sobreEyebrow','Etiqueta'),field('sobreLead','Texto de destaque','textarea'),field('sobreTexto','Biografia','textarea'),field('sobreBotao','Texto do botão'),field('profissionalImagem','Foto profissional','image'),field('depoimentosEyebrow','Etiqueta dos depoimentos'),field('depoimentosTitulo','Título dos depoimentos')],collection:{key:'depoimentos',label:'Depoimentos',template:{nome:'Cliente',texto:'Novo depoimento',estrelas:5,foto:''},fields:[['nome','Nome'],['texto','Depoimento','textarea'],['estrelas','Estrelas','number'],['foto','Foto','image']]}},
 social:{kicker:'Contato',title:'FAQ, endereço e redes',desc:'Configure dúvidas, horários, links e chamada de agendamento.',fields:[field('faqEyebrow','FAQ — etiqueta'),field('faqTitulo','FAQ — título'),field('faqTexto','FAQ — introdução','textarea'),field('localEyebrow','Local — etiqueta'),field('localTitulo','Local — título'),field('endereco','Endereço','textarea'),field('maps','Link do Google Maps','url'),field('agendamentoEyebrow','Agendamento — etiqueta'),field('agendamentoTitulo','Agendamento — título'),field('agendamentoTexto','Agendamento — texto','textarea'),field('whatsappBotao','Texto do botão WhatsApp'),field('instagramBotao','Texto do botão Instagram'),field('agendamentoNota','Observação'),field('whatsapp','WhatsApp','url'),field('instagram','Instagram','url'),field('tiktok','TikTok','url'),field('facebook','Facebook','url'),field('pinterest','Pinterest','url'),field('threads','Threads','url')],collections:[{key:'faq',label:'Perguntas frequentes',template:{pergunta:'Nova pergunta',resposta:'Nova resposta'},fields:[['pergunta','Pergunta'],['resposta','Resposta','textarea']]},{key:'horarios',label:'Horários',template:{dia:'Novo dia',hora:'Horário'},fields:[['dia','Dia'],['hora','Horário']]}]},
 dados:{kicker:'Gerenciamento',title:'Salvar e transferir',desc:'Backup, importação e restauração.',special:true}
};
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){
 nav.innerHTML=sections.map(([k,l],i)=>`<button type="button" data-panel="${k}" class="${i===0?'active':''}">${l}</button>`).join('');
 form.innerHTML=sections.map(([k],i)=>renderPanel(k,i===0)).join(''); bindAll();
}
function renderPanel(key,active){const p=panels[key];if(p.special)return `<section class="panel ${active?'active':''}" data-panel-content="${key}"><div class="panel-head"><small>${p.kicker}</small><h1>${p.title}</h1><p>${p.desc}</p></div><div class="data-actions"><button class="secondary" type="button" data-action="export">Exportar JSON</button><button class="secondary" type="button" data-action="import">Importar JSON</button><button class="secondary" type="button" data-action="download-html">Baixar configuração incorporada</button><button class="danger" type="button" data-action="reset">Restaurar padrão</button></div><p class="note">As imagens são comprimidas e salvas neste navegador. Para publicação real e múltiplos dispositivos, a próxima evolução é conectar o painel a um banco de dados e armazenamento em nuvem.</p></section>`;
 let html=`<section class="panel ${active?'active':''}" data-panel-content="${key}"><div class="panel-head"><small>${p.kicker}</small><h1>${p.title}</h1><p>${p.desc}</p></div>`+(p.fields||[]).map(f=>renderField(f.key,f.label,f.type,config[f.key])).join('');
 if(p.collection)html+=renderCollection(p.collection);(p.collections||[]).forEach(c=>html+=renderCollection(c));return html+'</section>'}
function renderField(key,label,type='text',value='',path=''){const full=path?`${path}.${key}`:key;if(type==='textarea')return `<label class="field"><span>${label}</span><textarea data-path="${full}">${esc(value||'')}</textarea></label>`;if(type==='image')return renderImage(full,label,value);if(type==='color')return `<label class="field"><span>${label}</span><div class="color-row"><input type="color" data-path="${full}" value="${esc(value||'#000000')}"><input type="text" data-color-text="${full}" value="${esc(value||'')}"></div></label>`;if(type==='checkbox')return `<label class="field"><span><input type="checkbox" data-path="${full}" ${value?'checked':''}> ${label}</span></label>`;if(type.startsWith('select:')){const opts=type.slice(7).split(',').map(x=>x.split('|'));return `<label class="field"><span>${label}</span><select data-path="${full}">${opts.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`}return `<label class="field"><span>${label}</span><input type="${type}" data-path="${full}" value="${esc(value??'')}"></label>`}
function renderImage(path,label,value){return `<div class="image-field"><span class="group-title">${label}</span><div class="image-field-preview" data-image-preview="${path}" style="${value?`background-image:url('${value}')`:''}">${value?'':'Nenhuma imagem selecionada'}</div><div class="image-actions"><label class="small-button" style="display:grid;place-items:center;cursor:pointer">Selecionar<input type="file" accept="image/*" data-image-input="${path}" hidden></label><button type="button" class="small-button" data-image-remove="${path}">Remover</button></div></div>`}
function renderCollection(c){const arr=getPath(c.key)||[];return `<div class="collection-block"><p class="group-title">${c.label}</p><div class="collection" data-collection="${c.key}">${arr.map((item,i)=>`<div class="collection-item"><div class="collection-item-head"><strong>${c.label} ${i+1}</strong><div class="item-actions"><button type="button" data-move="up" data-index="${i}" data-key="${c.key}">↑</button><button type="button" data-move="down" data-index="${i}" data-key="${c.key}">↓</button><button type="button" data-remove-item="${i}" data-key="${c.key}">×</button></div></div>${c.fields.map(([k,l,t='text'])=>renderField(k,l,t,item[k],`${c.key}.${i}`)).join('')}</div>`).join('')}</div><button type="button" class="add-button" data-add-item="${c.key}">+ Adicionar item</button></div>`}
function getPath(path,obj=config){return path.split('.').reduce((a,k)=>a?.[k],obj)}
function setPath(path,value,obj=config){const parts=path.split('.');let ref=obj;parts.slice(0,-1).forEach(k=>ref=ref[k]);ref[parts.at(-1)]=value}
function bindAll(){
 nav.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>switchPanel(b.dataset.panel));
 form.querySelectorAll('[data-path]').forEach(el=>el.addEventListener('input',()=>{let v=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;setPath(el.dataset.path,v);const ct=form.querySelector(`[data-color-text="${CSS.escape(el.dataset.path)}"]`);if(el.type==='color'&&ct)ct.value=el.value;changed()}));
 form.querySelectorAll('[data-color-text]').forEach(el=>el.addEventListener('change',()=>{if(/^#[0-9a-f]{6}$/i.test(el.value)){setPath(el.dataset.colorText,el.value);const c=form.querySelector(`[data-path="${CSS.escape(el.dataset.colorText)}"]`);if(c)c.value=el.value;changed()}}));
 form.querySelectorAll('[data-image-input]').forEach(el=>el.onchange=async()=>{if(!el.files[0])return;showToast('Processando imagem...');const data=await compressImage(el.files[0]);setPath(el.dataset.imageInput,data);changed();rerenderKeepPanel()});
 form.querySelectorAll('[data-image-remove]').forEach(b=>b.onclick=()=>{setPath(b.dataset.imageRemove,'');changed();rerenderKeepPanel()});
 form.querySelectorAll('[data-add-item]').forEach(b=>b.onclick=()=>{const c=findCollection(b.dataset.addItem);config[c.key]=config[c.key]||[];config[c.key].push(structuredClone(c.template));changed();rerenderKeepPanel()});
 form.querySelectorAll('[data-remove-item]').forEach(b=>b.onclick=()=>{config[b.dataset.key].splice(+b.dataset.removeItem,1);changed();rerenderKeepPanel()});
 form.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const a=config[b.dataset.key],i=+b.dataset.index,j=b.dataset.move==='up'?i-1:i+1;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];changed();rerenderKeepPanel()});
 form.querySelector('[data-action="export"]')?.addEventListener('click',exportConfig);form.querySelector('[data-action="import"]')?.addEventListener('click',()=>document.getElementById('jsonImport').click());form.querySelector('[data-action="reset"]')?.addEventListener('click',()=>{if(confirm('Restaurar todas as configurações?')){config=structuredClone(defaults);localStorage.removeItem(STORAGE_KEY);render();sendPreview();markSaved();showToast('Configuração restaurada.')}});form.querySelector('[data-action="download-html"]')?.addEventListener('click',downloadEmbedded);
}
function findCollection(key){for(const p of Object.values(panels)){if(p.collection?.key===key)return p.collection;const x=p.collections?.find(x=>x.key===key);if(x)return x}}
function switchPanel(k){nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.panel===k));form.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panelContent===k));form.scrollTop=0}
function activePanel(){return nav.querySelector('.active')?.dataset.panel||'marca'}function rerenderKeepPanel(){const k=activePanel();render();switchPanel(k)}
function changed(){dirty=true;document.querySelector('.editor-status').classList.add('unsaved');document.getElementById('saveStatus').textContent='Alterações não salvas';document.getElementById('saveTime').textContent='A prévia já foi atualizada';sendPreview()}
function markSaved(){dirty=false;document.querySelector('.editor-status').classList.remove('unsaved');document.getElementById('saveStatus').textContent='Alterações salvas';document.getElementById('saveTime').textContent='Salvo às '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(config));markSaved();sendPreview();showToast('Alterações salvas.')}catch(e){showToast('Limite do navegador atingido. Remova algumas imagens ou exporte o JSON.')}}
function sendPreview(){preview.contentWindow?.postMessage({type:'MN_PREVIEW',config},'*')}
function showToast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2500)}
async function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=()=>img.src=r.result;r.onerror=reject;img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};r.readAsDataURL(file)})}
function exportConfig(){const blob=new Blob([JSON.stringify(config,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mn-beauty-config.json';a.click();URL.revokeObjectURL(a.href);showToast('JSON exportado.')}
function downloadEmbedded(){const blob=new Blob([`window.MN_IMPORTED_CONFIG=${JSON.stringify(config)};`],{type:'text/javascript'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='config-publicacao.js';a.click();URL.revokeObjectURL(a.href)}
document.getElementById('jsonImport').onchange=async e=>{try{config={...defaults,...JSON.parse(await e.target.files[0].text())};render();sendPreview();save();showToast('Configuração importada.')}catch{showToast('JSON inválido.')}e.target.value=''};
document.getElementById('saveButton').onclick=save;document.getElementById('openSite').onclick=()=>{save();window.open('index.html','_blank','noopener')};document.getElementById('refreshPreview').onclick=()=>preview.src='index.html?preview=1&t='+Date.now();preview.onload=()=>setTimeout(sendPreview,80);
document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-device]').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('browserFrame').className='browser-frame '+b.dataset.device});
const sidebar=document.querySelector('.editor-sidebar');document.getElementById('openSidebar').onclick=()=>sidebar.classList.add('open');document.getElementById('closeSidebar').onclick=()=>sidebar.classList.remove('open');window.addEventListener('beforeunload',e=>{if(dirty)e.preventDefault()});render();markSaved();
